#!/usr/bin/env sh

set -e

SIZE=normal
if test "$1" = "short"; then
  SIZE=short
  shift
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "missing jq!"
  exit 1
fi

TMP_FILE=/tmp/fear-and-greed

is_cache_valid() {
  # file exists and was last modified up to 1 hour ago
  test -f "$TMP_FILE" && find "$TMP_FILE" -mmin -"60" | grep -q .
}

if ! is_cache_valid; then
  response="$(curl -s 'https://api.alternative.me/fng/?limit=2')"
  if [ -n "$response" ]; then
    echo "$response" > "$TMP_FILE"
  else
    echo "internet?"
    exit 1
  fi
fi

response="$(cat "$TMP_FILE")"

today_value="$(echo "$response" | jq -r '.data[0].value')"
yesterday_value="$(echo "$response" | jq -r '.data[1].value')"
if [ "$today_value" -ge "$yesterday_value" ]; then
  equation="($today_value-$yesterday_value)*100/$yesterday_value"
else
  sign="-"
  equation="($yesterday_value-$today_value)*100/$yesterday_value"
fi
change_percent="$sign$(echo "scale = 2 ; $equation" | bc)"

today_classification="$(echo "$response" | jq -r '.data[0].value_classification')"
if [ "$today_classification" = "Fear" ] || [ "$today_classification" = "Greed" ] || [ "$today_classification" = "Neutral" ]; then
  today_label="$(printf '%s' "$today_classification" | cut -c 1)"
else
  # e.g.: Extreme Fear. I want these to be in full!!!
  today_label=" $today_classification"
fi

if test "$SIZE" = "normal"; then
  printf "F&G: %s%s (%s%%)" "$today_value" "$today_label" "$change_percent"
else
  printf "F&G: %s" "$today_value"
fi
