---
# install fzf
- hosts: 127.0.0.1
  connection: local

  # NOTE(hwoarang) The 'apt' module needs python-apt installed in the virtualenv
  # but it's not possible to do that. See https://github.com/ansible/ansible/issues/14468
  # python-apt only works if it's installed on the local system so we need to switch the
  # Ansible python interpreter.
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Enable restricted repos
      become: yes
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted"
        - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
        - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"
        - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security multiverse"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"

    - name: Install general tools
      become: yes
      apt:
        name:
          - curl
          - git
          - wget

    - name: Install fonts I love
      become: yes
      apt:
        name:
          - fonts-hack-ttf
          - fonts-inconsolata
          - fonts-firacode

    - name: Install tooling I love
      become: yes
      apt:
        name:
          - fish
          - tmux
