---
# install fzf
- hosts: 127.0.0.1
  connection: local

  # NOTE(hwoarang) The 'apt' module needs python-apt installed in the virtualenv
  # but it's not possible to do that. See https://github.com/ansible/ansible/issues/14468
  # python-apt only works if it's installed on the local system so we need to switch the
  # Ansible python interpreter.
  vars:
    ansible_python_interpreter: /usr/bin/python3
    dmenu_version: '5.0'
    asdf_versions_wanted:
      - { plugin: ruby, version: 2.7.1, global: yes }
      - { plugin: python, version: 3.8.2, global: yes }
      - { plugin: rust, version: 1.46.0, global: yes }

  tasks:
    - name: Enable restricted repos
      become: yes
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} main restricted"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates main restricted"
        - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security main restricted"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe"
        - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security universe"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} multiverse"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"
        - "deb http://security.ubuntu.com/ubuntu {{ ansible_distribution_release }}-security multiverse"
        - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-backports main restricted universe multiverse"

    - name: Install general tools
      become: yes
      apt:
        name:
          - curl
          - git
          - wget

    - name: Install fonts I love
      become: yes
      apt:
        name:
          - fonts-hack-ttf
          - fonts-inconsolata
          - fonts-firacode

    - name: Install tooling I love
      become: yes
      apt:
        name:
          - fish
          - tmux

    - include_tasks: tooling_tasks/install_asdf.yml

    - name: Register installed dmenu version
      command: dmenu -v
      register: installed_dmenu_version
      ignore_errors: yes
      changed_when: no

    - include_tasks: tooling_tasks/install_dmenu.yml
      when: installed_dmenu_version.failed or dmenu_version not in installed_dmenu_version.stdout
