---
- hosts: 127.0.0.1
  connection: local

  vars:
    dotfiles_path: $HOME/dotfiles

  vars_files: [vars.yml]

  tasks:
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - $HOME/.config/alacritty
        - $HOME/.config/fish/functions

    - name: Setup .gitconfig
      template:
        src: ../git_files/.gitconfig.j2
        dest: ../git_files/.gitconfig

    - name: Symlinks $HOME dotfiles
      file:
        src: "{{ dotfiles_path }}/{{ item.src }}"
        dest: "$HOME/{{ item.dest }}"
        state: link
        force: yes
      with_items:
        - { src: .vimrc, dest: .vimrc }
        - { src: .tmux.conf, dest: .tmux.conf }
        - { src: .tmux-osx.conf, dest: .tmux-osx.conf }
        - { src: git_files/.gitmessage, dest: .gitmessage }
        - { src: git_files/.gitignore, dest: .gitignore }
        - { src: git_files/.gitconfig, dest: .gitconfig }
        - { src: .config/fish/config.fish, dest: .config/fish/config.fish }
        - { src: .config/fish/fishfile, dest: .config/fish/fishfile }
        - { src: .config/fish/functions/fish_prompt.fish, dest: .config/fish/functions/fish_prompt.fish }
        - { src: .config/fish/functions/fish_right_prompt.fish, dest: .config/fish/functions/fish_right_prompt.fish }
        - { src: .config/termite/config, dest: .config/termite/config }
        - { src: .config/alacritty/alacritty.yml, dest: .config/alacritty/alacritty.yml }

